version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mixi_db
    restart: always
    environment:
      MYSQL_DATABASE: mixi_shop
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./DB/mixi_shop.sql:/docker-entrypoint-initdb.d/mixi_shop.sql
    networks:
      - mixi_network

  web:
    image: doanasd/mixi_shop:latest
    container_name: mixi_app
    restart: always
    # XÓA phần ports ở đây để ẩn container web khỏi internet
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - mixi_network

  # THÊM SERVICE WAF MỚI
  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: mixi_waf
    restart: always
    ports:
      - "8080:8080" # Bây giờ WAF sẽ là người giữ cửa ở cổng 8080
    environment:
      - BACKEND=http://web:80 # Chỉ đường cho WAF đẩy traffic sạch vào container web
      - MODSEC_RULE_ENGINE=On # Bật chế độ chặn chủ động (Block)
    depends_on:
      - web
    networks:
      - mixi_network

networks:
  mixi_network:
    driver: bridge
